[package]
name = "frames"
version = "0.1.0"
authors = ["jesskfulwood <jesskfulwood@gmail.com>"]

[dependencies]
failure = "0.1.1"
num = "0.2.0"
new-ordered-float = "1.0.1"
csv = "1.0.0"

[dev-dependencies]
tempdir = "0.3.7"
